// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDONdHWlZzcaydCJfh05qg-VDTdEIc3R7w',
    appId: '1:605329036211:web:ddf9c3dc4d3231663731c6',
    messagingSenderId: '605329036211',
    projectId: 'shophelper-ce6e4',
    authDomain: 'shophelper-ce6e4.firebaseapp.com',
    storageBucket: 'shophelper-ce6e4.firebasestorage.app',
    measurementId: 'G-1CECSGPXYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6QHhEf-ED42lhK_3k2N21D2fE-OeiYN8',
    appId: '1:605329036211:android:1b7ac3701b0345f83731c6',
    messagingSenderId: '605329036211',
    projectId: 'shophelper-ce6e4',
    storageBucket: 'shophelper-ce6e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhNsz28eN-i42ThyGu_6g_fItwVukE1j4',
    appId: '1:605329036211:ios:8d8ea9e9e59111073731c6',
    messagingSenderId: '605329036211',
    projectId: 'shophelper-ce6e4',
    storageBucket: 'shophelper-ce6e4.firebasestorage.app',
    iosBundleId: 'com.example.shopHelperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhNsz28eN-i42ThyGu_6g_fItwVukE1j4',
    appId: '1:605329036211:ios:8d8ea9e9e59111073731c6',
    messagingSenderId: '605329036211',
    projectId: 'shophelper-ce6e4',
    storageBucket: 'shophelper-ce6e4.firebasestorage.app',
    iosBundleId: 'com.example.shopHelperApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDONdHWlZzcaydCJfh05qg-VDTdEIc3R7w',
    appId: '1:605329036211:web:b29e4cc42c0db7d13731c6',
    messagingSenderId: '605329036211',
    projectId: 'shophelper-ce6e4',
    authDomain: 'shophelper-ce6e4.firebaseapp.com',
    storageBucket: 'shophelper-ce6e4.firebasestorage.app',
    measurementId: 'G-PMZRGYH08Z',
  );
}
